IF(SYMENGINE_INCLUDE_DIRS)
	# Already in cache, be silent
	SET(SYMENGINE_FIND_QUIETLY TRUE)
ENDIF(SYMENGINE_INCLUDE_DIRS)

INCLUDE(FindPackageHandleStandardArgs)

find_package(SymEngine REQUIRED)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SymEngine DEFAULT_MSG SYMENGINE_INCLUDE_DIRS SYMENGINE_LIBRARIES)

MARK_AS_ADVANCED(SYMENGINE_INCLUDE_DIRS SYMENGINE_LIBRARIES)

if(SymEngine_FOUND AND NOT TARGET SymEngine::symengine)
    add_library(SymEngine::symengine UNKNOWN IMPORTED)
    set_target_properties(SymEngine::symengine 
        PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${SYMENGINE_INCLUDE_DIRS}" IMPORTED_LOCATION "${SYMENGINE_LIBRARIES}")
endif()
