#include <iostream>
#include <iomanip>
#include <random>
#include <cmath>

#include "../src/dcgp.hpp"

bool test_fails(
        unsigned int r,
        unsigned int c,
        unsigned int l,
        unsigned int N) // number of samples
{
   dcgp::function_set basic_set({"sum","diff","mul","div"});
   dcgp::expression ex(1, 1, r, c, l, basic_set(), 123);

    // 1) we create N data points 
    std::default_random_engine re(12);
    std::vector<std::vector<double> > in;
    std::vector<std::vector<double> > out;
    std::vector<double> in_point(1);
    std::vector<double> out_point(1);

    // Koza quintic polynomial x^5 - 2x^3 + x
    std::function<double(double)> f = [](double x){return x*x*x*x*x - 2*x*x*x + x;};
    for (auto i = 0u; i < N; ++i)
    {
        in_point[0] = std::uniform_real_distribution<double>(-1, 1)(re);
        out_point[0] = f(in_point[0]);
        in.push_back(in_point);
        out.push_back(out_point);
    }

    /// 2) we use a simple ES(1+4) to evolve an expression that represents our target
    /// note that the problem is a maximization problem
    double best_fit = 0;
    std::vector<double> newfits(4,0.);
    std::vector<std::vector<unsigned int> > newchromosomes(4);
    std::vector<unsigned int> best_chromosome;
    unsigned int gen = 0;
    do
    {
        gen++;
        for (auto i = 0u; i < newfits.size(); ++i) {
            ex.mutate_active();
            newfits[i] = simple_data_fit(ex, in, out); //, dcgp::program::HITS_BASED);
            newchromosomes[i] = ex.get();
        }
        for (auto i = 0u; i < newfits.size(); ++i) {
            if (newfits[i] >= best_fit) {
                best_fit = newfits[i];
                best_chromosome = newchromosomes[i];
            }
        }

    } while (best_fit < N);
    ex.set(best_chromosome);
    std::vector<std::string> in_sym({"x"});
    std::cout << "Number of generations: " << gen << std::endl;
    std::cout << "Final expression: " << ex(in_sym) << std::endl;
    return false;
}

/// This tests that computing the fitness on data generated by the expression encoded in a program 
/// correctly account for a zero error
int main() {
    return test_fails(1,15,16, 10);
}

#undef TOL
