#ifndef DCGP_WRAPPED_FUNCTIONS_S11N_IMPLEMENT_H
#define DCGP_WRAPPED_FUNCTIONS_S11N_IMPLEMENT_H

#include <dcgp/wrapped_functions.hpp>

DCGP_S11N_FUNCTION_IMPLEMENT_MULTI(my_diff)
DCGP_S11N_FUNCTION_IMPLEMENT_MULTI(my_sqrt)

#endif
